### ISSUE TITLE
Fix update command from Discord

### ISSUE THREAD

**Issue by RaFaTEOLI** [RaFaTEOLI/discord-bot-api-queue#6]
Currently we update the command on discord using the command name, however if the name changes, we will be creating a new command.

**Tasks**:

- [x] Update `remote-update-command-status` usecase to handle `discordId` to call `discord-bot-api` with `discordId`.

- [x] Rename `remote-update-command-status` usecase to `remote-update-command`.

- [x] Update `remote-save-command` usecase to use `discordId` to call discord application api to update the command by id:

```javascript

let url: string = this.url;
let method: HttpMethod = 'post';

if (data.discordId) {
      url = `${this.url}/${data.discordId}`;
      method = 'patch';
}

```

- [x] Update `remote-save-command` to return `discordId` retrieved from discord application api post response.

- [x] Retrieve from `discordId` from queue factory and pass it into queue ack function.

```javascript

const response = await queue.factory.save(payload);

channel.ack(message);
console.log(`☑️ [${queue.action}] Acknowledged '%s'`, message.content.toString());

if (queue.ack) {
      try {
            await queue.ack.function[queue.ack.functionName](id, queue.ack.successPayload(response));
            console.log(`☑️ [${queue.action}] Acknowledged Function '%s'`, queue.ack.functionName);
      } catch (err) {
            console.error('❌ Error while trying to call acknowledge function:', err.message);
      }
 }

```
